"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.AdvancedSearchDirect = exports.PerformanceDirect = exports.RecruitmentDirect = exports.TrainingDirect = exports.DocumentsDirect = exports.PayrollDirect = exports.LeaveRequestsDirect = exports.AttendanceDirect = exports.SettingsDirect = exports.ReportsDirect = exports.EmployeesDirect = exports.CompanyDetailsDirect = exports.CompaniesDirect = exports.DashboardDirect = exports.NotFoundDirect = exports.LoginDirect = exports.CompanySelectionDirect = exports.I18nTest = exports.AIAnalytics = exports.AIChatbotDemo = exports.LayoutExample = exports.EmployeeManagement = exports.SuperAdminDashboard = exports.RoleBasedDashboard = exports.PermissionTest = exports.NotificationTest = exports.SignatureTest = exports.Signatures = exports.Leaves = exports.Licenses = exports.GovernmentForms = exports.AccountingSystems = exports.AIDashboard = exports.AdvancedSearch = exports.Performance = exports.Recruitment = exports.Training = exports.Documents = exports.Payroll = exports.LeaveRequests = exports.Attendance = exports.Settings = exports.Reports = exports.Employees = exports.CompanyDetails = exports.Companies = exports.Dashboard = exports.NotFound = exports.Login = exports.CompanySelection = void 0;
exports.GovernmentFormsDirect = exports.AccountingSystemsDirect = exports.AIDashboardDirect = void 0;
// Lazy-loaded pages exports for better performance
var lazy_pages_1 = require("./lazy-pages");
Object.defineProperty(exports, "CompanySelection", { enumerable: true, get: function () { return lazy_pages_1.CompanySelection; } });
Object.defineProperty(exports, "Login", { enumerable: true, get: function () { return lazy_pages_1.Login; } });
Object.defineProperty(exports, "NotFound", { enumerable: true, get: function () { return lazy_pages_1.NotFound; } });
Object.defineProperty(exports, "Dashboard", { enumerable: true, get: function () { return lazy_pages_1.Dashboard; } });
Object.defineProperty(exports, "Companies", { enumerable: true, get: function () { return lazy_pages_1.Companies; } });
Object.defineProperty(exports, "CompanyDetails", { enumerable: true, get: function () { return lazy_pages_1.CompanyDetails; } });
Object.defineProperty(exports, "Employees", { enumerable: true, get: function () { return lazy_pages_1.Employees; } });
Object.defineProperty(exports, "Reports", { enumerable: true, get: function () { return lazy_pages_1.Reports; } });
Object.defineProperty(exports, "Settings", { enumerable: true, get: function () { return lazy_pages_1.Settings; } });
Object.defineProperty(exports, "Attendance", { enumerable: true, get: function () { return lazy_pages_1.Attendance; } });
Object.defineProperty(exports, "LeaveRequests", { enumerable: true, get: function () { return lazy_pages_1.LeaveRequests; } });
Object.defineProperty(exports, "Payroll", { enumerable: true, get: function () { return lazy_pages_1.Payroll; } });
Object.defineProperty(exports, "Documents", { enumerable: true, get: function () { return lazy_pages_1.Documents; } });
Object.defineProperty(exports, "Training", { enumerable: true, get: function () { return lazy_pages_1.Training; } });
Object.defineProperty(exports, "Recruitment", { enumerable: true, get: function () { return lazy_pages_1.Recruitment; } });
Object.defineProperty(exports, "Performance", { enumerable: true, get: function () { return lazy_pages_1.Performance; } });
Object.defineProperty(exports, "AdvancedSearch", { enumerable: true, get: function () { return lazy_pages_1.AdvancedSearch; } });
Object.defineProperty(exports, "AIDashboard", { enumerable: true, get: function () { return lazy_pages_1.AIDashboard; } });
Object.defineProperty(exports, "AccountingSystems", { enumerable: true, get: function () { return lazy_pages_1.AccountingSystems; } });
Object.defineProperty(exports, "GovernmentForms", { enumerable: true, get: function () { return lazy_pages_1.GovernmentForms; } });
Object.defineProperty(exports, "Licenses", { enumerable: true, get: function () { return lazy_pages_1.Licenses; } });
Object.defineProperty(exports, "Leaves", { enumerable: true, get: function () { return lazy_pages_1.Leaves; } });
Object.defineProperty(exports, "Signatures", { enumerable: true, get: function () { return lazy_pages_1.Signatures; } });
Object.defineProperty(exports, "SignatureTest", { enumerable: true, get: function () { return lazy_pages_1.SignatureTest; } });
Object.defineProperty(exports, "NotificationTest", { enumerable: true, get: function () { return lazy_pages_1.NotificationTest; } });
Object.defineProperty(exports, "PermissionTest", { enumerable: true, get: function () { return lazy_pages_1.PermissionTest; } });
Object.defineProperty(exports, "RoleBasedDashboard", { enumerable: true, get: function () { return lazy_pages_1.RoleBasedDashboard; } });
Object.defineProperty(exports, "SuperAdminDashboard", { enumerable: true, get: function () { return lazy_pages_1.SuperAdminDashboard; } });
Object.defineProperty(exports, "EmployeeManagement", { enumerable: true, get: function () { return lazy_pages_1.EmployeeManagement; } });
Object.defineProperty(exports, "LayoutExample", { enumerable: true, get: function () { return lazy_pages_1.LayoutExample; } });
Object.defineProperty(exports, "AIChatbotDemo", { enumerable: true, get: function () { return lazy_pages_1.AIChatbotDemo; } });
Object.defineProperty(exports, "AIAnalytics", { enumerable: true, get: function () { return lazy_pages_1.AIAnalytics; } });
Object.defineProperty(exports, "I18nTest", { enumerable: true, get: function () { return lazy_pages_1.I18nTest; } });
// Direct exports for backward compatibility (deprecated - use lazy versions instead)
var company_selection_1 = require("./company-selection");
Object.defineProperty(exports, "CompanySelectionDirect", { enumerable: true, get: function () { return __importDefault(company_selection_1).default; } });
var login_1 = require("./login");
Object.defineProperty(exports, "LoginDirect", { enumerable: true, get: function () { return __importDefault(login_1).default; } });
var not_found_1 = require("./not-found");
Object.defineProperty(exports, "NotFoundDirect", { enumerable: true, get: function () { return __importDefault(not_found_1).default; } });
var dashboard_1 = require("./dashboard");
Object.defineProperty(exports, "DashboardDirect", { enumerable: true, get: function () { return __importDefault(dashboard_1).default; } });
var companies_1 = require("./companies");
Object.defineProperty(exports, "CompaniesDirect", { enumerable: true, get: function () { return __importDefault(companies_1).default; } });
var company_details_1 = require("./company-details");
Object.defineProperty(exports, "CompanyDetailsDirect", { enumerable: true, get: function () { return __importDefault(company_details_1).default; } });
var employees_1 = require("./employees");
Object.defineProperty(exports, "EmployeesDirect", { enumerable: true, get: function () { return __importDefault(employees_1).default; } });
var reports_1 = require("./reports");
Object.defineProperty(exports, "ReportsDirect", { enumerable: true, get: function () { return __importDefault(reports_1).default; } });
var settings_1 = require("./settings");
Object.defineProperty(exports, "SettingsDirect", { enumerable: true, get: function () { return __importDefault(settings_1).default; } });
var attendance_1 = require("./attendance");
Object.defineProperty(exports, "AttendanceDirect", { enumerable: true, get: function () { return __importDefault(attendance_1).default; } });
var leave_requests_1 = require("./leave-requests");
Object.defineProperty(exports, "LeaveRequestsDirect", { enumerable: true, get: function () { return __importDefault(leave_requests_1).default; } });
var payroll_1 = require("./payroll");
Object.defineProperty(exports, "PayrollDirect", { enumerable: true, get: function () { return __importDefault(payroll_1).default; } });
var documents_1 = require("./documents");
Object.defineProperty(exports, "DocumentsDirect", { enumerable: true, get: function () { return __importDefault(documents_1).default; } });
var training_1 = require("./training");
Object.defineProperty(exports, "TrainingDirect", { enumerable: true, get: function () { return __importDefault(training_1).default; } });
var recruitment_1 = require("./recruitment");
Object.defineProperty(exports, "RecruitmentDirect", { enumerable: true, get: function () { return __importDefault(recruitment_1).default; } });
var performance_1 = require("./performance");
Object.defineProperty(exports, "PerformanceDirect", { enumerable: true, get: function () { return __importDefault(performance_1).default; } });
var advanced_search_1 = require("./advanced-search");
Object.defineProperty(exports, "AdvancedSearchDirect", { enumerable: true, get: function () { return __importDefault(advanced_search_1).default; } });
var ai_dashboard_1 = require("./ai-dashboard");
Object.defineProperty(exports, "AIDashboardDirect", { enumerable: true, get: function () { return __importDefault(ai_dashboard_1).default; } });
var accounting_systems_1 = require("./accounting-systems");
Object.defineProperty(exports, "AccountingSystemsDirect", { enumerable: true, get: function () { return __importDefault(accounting_systems_1).default; } });
var government_forms_1 = require("./government-forms");
Object.defineProperty(exports, "GovernmentFormsDirect", { enumerable: true, get: function () { return __importDefault(government_forms_1).default; } });
