"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LoggingErrorBoundary = exports.ProtectedGovernmentFormsPage = exports.ProtectedAccountingSystemsPage = exports.ProtectedAIDashboardPage = exports.ProtectedAdvancedSearchPage = exports.ProtectedPerformancePage = exports.ProtectedRecruitmentPage = exports.ProtectedTrainingPage = exports.ProtectedDocumentsPage = exports.ProtectedPayrollPage = exports.ProtectedLeaveRequestsPage = exports.ProtectedAttendancePage = exports.ProtectedSettingsPage = exports.ProtectedReportsPage = exports.ProtectedEmployeesPage = exports.ProtectedCompaniesPage = exports.ProtectedRoute = exports.InitializationDebugger = exports.AppInitializer = exports.LoadingSpinner = exports.ErrorMessage = exports.PageHelmets = exports.PageHelmet = exports.usePageMeta = exports.HelmetProvider = exports.OverlayLoading = exports.ComponentLoadingFallback = exports.PageLoadingFallback = exports.LoadingFallback = exports.OverlayLoadingScreen = exports.CompactLoadingScreen = exports.LoadingScreen = exports.NetworkErrorFallback = exports.SimpleErrorFallback = exports.withErrorBoundary = exports.ErrorBoundary = void 0;
// Core Components
var ErrorBoundary_1 = require("./ErrorBoundary");
Object.defineProperty(exports, "ErrorBoundary", { enumerable: true, get: function () { return ErrorBoundary_1.ErrorBoundary; } });
Object.defineProperty(exports, "withErrorBoundary", { enumerable: true, get: function () { return ErrorBoundary_1.withErrorBoundary; } });
Object.defineProperty(exports, "SimpleErrorFallback", { enumerable: true, get: function () { return ErrorBoundary_1.SimpleErrorFallback; } });
Object.defineProperty(exports, "NetworkErrorFallback", { enumerable: true, get: function () { return ErrorBoundary_1.NetworkErrorFallback; } });
var LoadingScreen_1 = require("./LoadingScreen");
Object.defineProperty(exports, "LoadingScreen", { enumerable: true, get: function () { return LoadingScreen_1.LoadingScreen; } });
Object.defineProperty(exports, "CompactLoadingScreen", { enumerable: true, get: function () { return LoadingScreen_1.CompactLoadingScreen; } });
Object.defineProperty(exports, "OverlayLoadingScreen", { enumerable: true, get: function () { return LoadingScreen_1.OverlayLoadingScreen; } });
var LoadingFallback_1 = require("./LoadingFallback");
Object.defineProperty(exports, "LoadingFallback", { enumerable: true, get: function () { return LoadingFallback_1.LoadingFallback; } });
Object.defineProperty(exports, "PageLoadingFallback", { enumerable: true, get: function () { return LoadingFallback_1.PageLoadingFallback; } });
Object.defineProperty(exports, "ComponentLoadingFallback", { enumerable: true, get: function () { return LoadingFallback_1.ComponentLoadingFallback; } });
Object.defineProperty(exports, "OverlayLoading", { enumerable: true, get: function () { return LoadingFallback_1.OverlayLoadingFallback; } });
var HelmetProvider_1 = require("./HelmetProvider");
Object.defineProperty(exports, "HelmetProvider", { enumerable: true, get: function () { return HelmetProvider_1.HelmetProvider; } });
Object.defineProperty(exports, "usePageMeta", { enumerable: true, get: function () { return HelmetProvider_1.usePageMeta; } });
var PageHelmet_1 = require("./PageHelmet");
Object.defineProperty(exports, "PageHelmet", { enumerable: true, get: function () { return PageHelmet_1.PageHelmet; } });
Object.defineProperty(exports, "PageHelmets", { enumerable: true, get: function () { return PageHelmet_1.PageHelmets; } });
var ErrorMessage_1 = require("./ErrorMessage");
Object.defineProperty(exports, "ErrorMessage", { enumerable: true, get: function () { return ErrorMessage_1.ErrorMessage; } });
var LoadingSpinner_1 = require("./LoadingSpinner");
Object.defineProperty(exports, "LoadingSpinner", { enumerable: true, get: function () { return LoadingSpinner_1.LoadingSpinner; } });
// App Initialization
var AppInitializer_1 = require("./AppInitializer");
Object.defineProperty(exports, "AppInitializer", { enumerable: true, get: function () { return AppInitializer_1.AppInitializer; } });
Object.defineProperty(exports, "InitializationDebugger", { enumerable: true, get: function () { return AppInitializer_1.InitializationDebugger; } });
// Route Protection
var ProtectedRoute_1 = require("./ProtectedRoute");
Object.defineProperty(exports, "ProtectedRoute", { enumerable: true, get: function () { return ProtectedRoute_1.ProtectedRoute; } });
var ProtectedPage_1 = require("./ProtectedPage");
Object.defineProperty(exports, "ProtectedCompaniesPage", { enumerable: true, get: function () { return ProtectedPage_1.ProtectedCompaniesPage; } });
Object.defineProperty(exports, "ProtectedEmployeesPage", { enumerable: true, get: function () { return ProtectedPage_1.ProtectedEmployeesPage; } });
Object.defineProperty(exports, "ProtectedReportsPage", { enumerable: true, get: function () { return ProtectedPage_1.ProtectedReportsPage; } });
Object.defineProperty(exports, "ProtectedSettingsPage", { enumerable: true, get: function () { return ProtectedPage_1.ProtectedSettingsPage; } });
Object.defineProperty(exports, "ProtectedAttendancePage", { enumerable: true, get: function () { return ProtectedPage_1.ProtectedAttendancePage; } });
Object.defineProperty(exports, "ProtectedLeaveRequestsPage", { enumerable: true, get: function () { return ProtectedPage_1.ProtectedLeaveRequestsPage; } });
Object.defineProperty(exports, "ProtectedPayrollPage", { enumerable: true, get: function () { return ProtectedPage_1.ProtectedPayrollPage; } });
Object.defineProperty(exports, "ProtectedDocumentsPage", { enumerable: true, get: function () { return ProtectedPage_1.ProtectedDocumentsPage; } });
Object.defineProperty(exports, "ProtectedTrainingPage", { enumerable: true, get: function () { return ProtectedPage_1.ProtectedTrainingPage; } });
Object.defineProperty(exports, "ProtectedRecruitmentPage", { enumerable: true, get: function () { return ProtectedPage_1.ProtectedRecruitmentPage; } });
Object.defineProperty(exports, "ProtectedPerformancePage", { enumerable: true, get: function () { return ProtectedPage_1.ProtectedPerformancePage; } });
Object.defineProperty(exports, "ProtectedAdvancedSearchPage", { enumerable: true, get: function () { return ProtectedPage_1.ProtectedAdvancedSearchPage; } });
Object.defineProperty(exports, "ProtectedAIDashboardPage", { enumerable: true, get: function () { return ProtectedPage_1.ProtectedAIDashboardPage; } });
Object.defineProperty(exports, "ProtectedAccountingSystemsPage", { enumerable: true, get: function () { return ProtectedPage_1.ProtectedAccountingSystemsPage; } });
Object.defineProperty(exports, "ProtectedGovernmentFormsPage", { enumerable: true, get: function () { return ProtectedPage_1.ProtectedGovernmentFormsPage; } });
// Enhanced Error Boundary
var logger_1 = require("../../lib/logger");
Object.defineProperty(exports, "LoggingErrorBoundary", { enumerable: true, get: function () { return logger_1.LoggingErrorBoundary; } });
